CREATE TABLE `tb_workresourceinfo` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `WorkOrderId` char(12) DEFAULT NULL COMMENT '工单主单主键(tb_workorderinfo.Id);人员招募信息表ID(tb_staffacquisitioninfo.Id)',
  `GoodsDetailId` char(12) DEFAULT NULL COMMENT '设备明细表Id(tb_workgoodsdetail.Id)；回款提报表Id(tb_afcreturnedmoney.Id)\n；金融谈判记录信息表Id(tb_afcnegotiationrecordinfo.Id);工单服务科目信息表(tb_workservicesubject.Id)',
  `ResourceName` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '附件名称',
  `ResourceId` char(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '资源表Id(basic_resourceitem.Id)',
  `SourceType` smallint(6) DEFAULT NULL COMMENT '图片类型(1设备参照图片2AFC主单附件3AFC费用附件4AFC备案附件5主单附件6收件附件7VHS备案附件8归还附件 9二手车检测报告10AFC路况异常附件11在线支付费用附件12VHS服务凭证13退单凭证14回款提报还款凭证 15回款提报谈判记录 16回款提报其他 17VHS邮寄凭证18 金融预约附件 19 金融备案视频附件20 谈判记录附件 21 营业执照 22 相关资质证书 23 车务ETC附件 24 通用异常签到附件\n25车管工单附件 26AFC住宿打卡附件 27VHS请求关闭退单凭证 28下单附件 29科目附件 30服务结果附件 31异常反馈附件32勘测附件33安装附件34增项费附件35增项费付款附件36勘测费付款附件37AFC二访附件38车务补录附件39车务工单PDF报告)',
  `Duration` int(11) DEFAULT NULL COMMENT '录音或视频时长（单位/秒）',
  `RemindContent` varchar(200) DEFAULT NULL COMMENT '提醒内容(basic_accessoryrule.RemindContent)',
  `Remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `ResourceTag` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户附件特殊标记',
  `ComparisonResults` int(11) DEFAULT NULL COMMENT '附件对比结果（0不一致 1一致）',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime DEFAULT NULL,
  `UpdateById` char(36) DEFAULT NULL COMMENT '更新人Id',
  `UpdateAt` datetime DEFAULT NULL COMMENT '更新时间',
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime DEFAULT NULL,
  `Deleted` tinyint(1) NOT NULL DEFAULT '0',
  `ResourceCode` char(12) DEFAULT NULL COMMENT '基础附件信息Id(basic_accessoryresource.Id)',
  `ImageAddressUrl` varchar(200) DEFAULT NULL COMMENT '附件经纬度链接',
  `ResourceClassName` varchar(50) DEFAULT NULL COMMENT '附件类别',
  `IsOcrCheck` smallint(6) DEFAULT NULL COMMENT 'OCR识别状态：0.未识别；1.已识别;',
  PRIMARY KEY (`Id`),
  KEY `NON-GoodsDetailId` (`GoodsDetailId`),
  KEY `NON-WorkOrderId` (`WorkOrderId`),
  KEY `NON-ResourceId` (`ResourceId`),
  KEY `NON-SourceType` (`SourceType`)
) ENGINE=InnoDB AUTO_INCREMENT=294460114 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='工单附件表';


CREATE TABLE `basic_resourceitem` (
  `Id` char(12) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '主键(BR)',
  `Filename` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '文件名',
  `Url` text NOT NULL COMMENT '文件路径',
  `FileType` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '文件类型',
  `FileLength` bigint(20) DEFAULT NULL COMMENT '文件长度',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '信息录入人员',
  `CreatedAt` datetime DEFAULT NULL COMMENT '信息录入时间',
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '信息最后修改人员',
  `UpdatedAt` datetime DEFAULT NULL COMMENT '信息最后修改时间',
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '信息删除人员',
  `DeletedAt` datetime DEFAULT NULL COMMENT '信息删除时间',
  `Deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除标识',
  `FileSource` smallint(6) DEFAULT NULL COMMENT '附件上传来源：1.现场拍照；2.相册上传；3.PC上传；',
  `LastUpdateTimeStamp` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据变更时间戳',
  PRIMARY KEY (`Id`),
  KEY `idx_createdat` (`CreatedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文件信息表';

CREATE TABLE `workflowcompleteactivities` (
  `Id` char(36) NOT NULL COMMENT '工作流完成时活动日志表主键(GUID)',
  `RuntimeItemId` char(36) NOT NULL COMMENT '完成时工作流主键(workflowcompleteitems.Id)',
  `RuntimeStepId` char(36) DEFAULT NULL COMMENT '完成时工作流步骤主键(workflowcompletesteps.Id)',
  `UserId` char(36) DEFAULT NULL COMMENT '用户Id',
  `FullName` varchar(50) NOT NULL COMMENT '用户姓名',
  `Status` varchar(50) NOT NULL COMMENT '工作流完成时活动状态',
  `Message` longtext NOT NULL COMMENT '工作流完成时活动消息内容',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `FK_WorkflowCompleteActivities_WorkflowCompleteItems_RuntimeItem~` (`RuntimeItemId`),
  KEY `NON-RuntimeStepId` (`RuntimeStepId`),
  CONSTRAINT `FK_WorkflowCompleteActivities_WorkflowCompleteItems_RuntimeItem~` FOREIGN KEY (`RuntimeItemId`) REFERENCES `workflowcompleteitems` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `workflowcompleteactors` (
  `Id` char(36) NOT NULL COMMENT '工作流完成时处理人表主键(GUID)',
  `RuntimeStepId` char(36) NOT NULL COMMENT '完成时工作流步骤主键(workflowcompletesteps.Id)',
  `UserId` char(36) NOT NULL COMMENT '用户Id',
  `FullName` varchar(50) NOT NULL COMMENT '用户姓名',
  `LoginName` varchar(100) DEFAULT NULL COMMENT '用户登录名',
  `Notified` bit(1) NOT NULL COMMENT '是否通知',
  `NotifiedAt` datetime(6) DEFAULT NULL COMMENT '通知时间',
  `Remark` longtext COMMENT '工作流完成时处理人备注',
  `Processed` bit(1) NOT NULL COMMENT '是否处理',
  `ProcessedAt` datetime(6) DEFAULT NULL COMMENT '处理时间',
  `WorkflowHandlingStatusId` char(36) DEFAULT NULL COMMENT '工作流处理状态表主键(workflowhandlingstatus.Id)',
  `Status` varchar(50) DEFAULT NULL COMMENT '处理状态',
  `Active` bit(1) NOT NULL COMMENT '是否活动',
  `IsAgent` bit(1) NOT NULL COMMENT '是否为代理人',
  `AgentActorId` char(36) DEFAULT NULL COMMENT '指定处理人Id',
  `IsDelegate` bit(1) NOT NULL COMMENT '是否为委托人',
  `DelegateActorId` char(36) DEFAULT NULL COMMENT '委托人Id',
  `Reason` longtext COMMENT '指定处理人原因',
  `OriginName` varchar(50) DEFAULT NULL COMMENT '原处理人姓名',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_WorkflowCompleteActors_WorkflowHandlingStatusId` (`WorkflowHandlingStatusId`),
  KEY `NON-Active` (`Active`),
  KEY `NON-FullName` (`FullName`),
  KEY `NON-Processed` (`Processed`),
  KEY `IX_WorkflowCompleteActors_RuntimeStepId` (`RuntimeStepId`),
  CONSTRAINT `FK_WorkflowCompleteActors_WorkflowCompleteSteps_RuntimeStepId` FOREIGN KEY (`RuntimeStepId`) REFERENCES `workflowcompletesteps` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_WorkflowCompleteActors_WorkflowHandlingStatus_WorkflowHandli~` FOREIGN KEY (`WorkflowHandlingStatusId`) REFERENCES `workflowhandlingstatus` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `workflowcompleteattachments` (
  `Id` char(36) NOT NULL COMMENT '工作流完成时加签附件表主键(GUID)',
  `RuntimeCommentId` char(36) NOT NULL COMMENT '工作流完成时加签表主键(workflowcompletecomments.Id)',
  `Name` varchar(256) NOT NULL COMMENT '附件名称',
  `TargetUrl` varchar(500) NOT NULL COMMENT '附件URL',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_WorkflowCompleteAttachments_RuntimeCommentId` (`RuntimeCommentId`),
  CONSTRAINT `FK_WorkflowCompleteAttachments_WorkflowCompleteComments_Runtime~` FOREIGN KEY (`RuntimeCommentId`) REFERENCES `workflowcompletecomments` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


CREATE TABLE `workflowcompletecomments` (
  `Id` char(36) NOT NULL COMMENT '工作流完成时加签表主键(GUID)',
  `RuntimeActorId` char(36) NOT NULL COMMENT '工作流完成时处理人表主键(workflowcompleteactors.Id)',
  `FromUserId` char(36) NOT NULL COMMENT '用户Id(加签前)',
  `FromFullName` varchar(50) NOT NULL COMMENT '加签前用户姓名',
  `FromLoginName` varchar(100) DEFAULT NULL COMMENT '加签前用户登录名',
  `ToUserId` char(36) NOT NULL COMMENT '用户Id(加签后)',
  `ToFullName` varchar(50) NOT NULL COMMENT '加签后用户姓名',
  `ToLoginName` varchar(100) DEFAULT NULL COMMENT '加签后用户登录名',
  `CommentedAt` datetime(6) NOT NULL COMMENT '提交时间',
  `Comment` longtext NOT NULL COMMENT '加签备注',
  `Notified` bit(1) NOT NULL COMMENT '是否通知',
  `NotifiedAt` datetime(6) DEFAULT NULL COMMENT '通知时间',
  `IsReply` bit(1) NOT NULL COMMENT '否是回复加签',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_WorkflowCompleteComments_RuntimeActorId` (`RuntimeActorId`),
  CONSTRAINT `FK_WorkflowCompleteComments_WorkflowCompleteActors_RuntimeActor~` FOREIGN KEY (`RuntimeActorId`) REFERENCES `workflowcompleteactors` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


CREATE TABLE `workflowcompleteitems` (
  `Id` char(36) NOT NULL COMMENT '工作流完成时表主键(GUID)',
  `WorkflowItemId` char(36) NOT NULL COMMENT '设计时工作流主键(workflowitems.Id)',
  `TargetEntityId` varchar(50) NOT NULL COMMENT '工单主单主键(tb_workorderinfo.Id)',
  `CurrentStepId` char(36) DEFAULT NULL COMMENT '当前步骤表主键(workflowcompletesteps.Id)',
  `Status` varchar(50) NOT NULL COMMENT '处理状态',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `NON-TarGetId` (`TargetEntityId`),
  KEY `IX_WorkflowCompleteItems_CurrentStepId` (`CurrentStepId`),
  KEY `IX_WorkflowCompleteItems_WorkflowItemId` (`WorkflowItemId`),
  CONSTRAINT `FK_WorkflowCompleteItems_WorkflowCompleteSteps_CurrentStepId` FOREIGN KEY (`CurrentStepId`) REFERENCES `workflowcompletesteps` (`Id`),
  CONSTRAINT `FK_WorkflowCompleteItems_WorkflowItems_WorkflowItemId` FOREIGN KEY (`WorkflowItemId`) REFERENCES `workflowitems` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `workflowcompleterelatedactors` (
  `Id` char(36) NOT NULL COMMENT '工作流完成时步骤知情人表主键(GUID)',
  `RuntimeStepId` char(36) NOT NULL COMMENT '工作流完成时步骤表主键(workflowcompletesteps.Id)',
  `UserId` char(36) NOT NULL COMMENT '用户Id',
  `FullName` varchar(50) NOT NULL COMMENT '用户姓名',
  `LoginName` varchar(100) DEFAULT NULL COMMENT '用户登录名',
  `Status` varchar(50) DEFAULT NULL COMMENT '处理状态',
  `Notified` bit(1) NOT NULL COMMENT '是否通知',
  `NotifiedAt` datetime(6) DEFAULT NULL COMMENT '通知时间',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `FK_WorkflowCompleteRelatedActors_WorkflowCompleteSteps_RuntimeS~` (`RuntimeStepId`),
  CONSTRAINT `FK_WorkflowCompleteRelatedActors_WorkflowCompleteSteps_RuntimeS~` FOREIGN KEY (`RuntimeStepId`) REFERENCES `workflowcompletesteps` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `workflowcompletesteps` (
  `Id` char(36) NOT NULL COMMENT '工作流完成时步骤表主键(GUID)',
  `RuntimeItemId` char(36) NOT NULL COMMENT '完成时工作流主键(workflowcompleteitems.Id)',
  `WorkflowNodeId` char(36) DEFAULT NULL COMMENT '设计时工作流节点主键(workflownodes.Id)',
  `Name` varchar(256) NOT NULL COMMENT '步骤名称',
  `SortOrder` int(11) NOT NULL,
  `StartedAt` datetime(6) NOT NULL COMMENT '开始时间',
  `DoneAt` datetime(6) DEFAULT NULL COMMENT '结束时间',
  `ActorNumber` int(11) NOT NULL COMMENT '处理人数',
  `AcceptedNumber` int(11) NOT NULL COMMENT '通过人数',
  `DeclinedNumber` int(11) NOT NULL COMMENT '拒绝人数',
  `Status` varchar(50) DEFAULT NULL COMMENT '步骤状态',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_WorkflowCompleteSteps_WorkflowNodeId` (`WorkflowNodeId`),
  KEY `NON-Status` (`Status`),
  KEY `NON-DoneAt` (`DoneAt`),
  KEY `NON-Name` (`Name`),
  KEY `IX_WorkflowCompleteSteps_RuntimeItemId` (`RuntimeItemId`),
  KEY `NON-StartAt` (`StartedAt`),
  KEY `NON-SortOrder` (`SortOrder`),
  CONSTRAINT `FK_WorkflowCompleteSteps_WorkflowCompleteItems_RuntimeItemId` FOREIGN KEY (`RuntimeItemId`) REFERENCES `workflowcompleteitems` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_WorkflowCompleteSteps_WorkflowNodes_WorkflowNodeId` FOREIGN KEY (`WorkflowNodeId`) REFERENCES `workflownodes` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `workflowhandlingstatus` (
  `Id` char(36) NOT NULL COMMENT '工作流处理状态表主键(GUID)',
  `WorkflowNodeId` char(36) NOT NULL COMMENT '设计时工作流节点主键(workflownodes.Id)',
  `Code` varchar(50) NOT NULL COMMENT '处理状态编码',
  `Name` varchar(256) NOT NULL COMMENT '处理状态名称',
  `HandlingStatusType` varchar(50) NOT NULL COMMENT '处理状态类型',
  `SortOrder` int(11) NOT NULL,
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  `LastUpdateTimeStamp` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据变更时间戳',
  PRIMARY KEY (`Id`),
  KEY `IX_WorkflowHandlingStatus_WorkflowNodeId` (`WorkflowNodeId`),
  CONSTRAINT `FK_WorkflowHandlingStatus_WorkflowNodes_WorkflowNodeId` FOREIGN KEY (`WorkflowNodeId`) REFERENCES `workflownodes` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `workflowruntimeactivities` (
  `Id` char(36) NOT NULL COMMENT '工作流进行时活动日志表主键(GUID)',
  `RuntimeItemId` char(36) NOT NULL COMMENT '进行时工作流主键(workflowruntimeitems.Id)',
  `RuntimeStepId` char(36) DEFAULT NULL COMMENT '进行时工作流步骤主键(workflowruntimesteps.Id)',
  `UserId` char(36) DEFAULT NULL COMMENT '用户Id',
  `FullName` varchar(50) NOT NULL COMMENT '用户姓名',
  `Status` varchar(50) NOT NULL COMMENT '工作流完成时活动状态',
  `Message` longtext NOT NULL COMMENT '工作流完成时活动消息内容',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `NON-RuntimeStepId` (`RuntimeStepId`),
  KEY `IX_WorkflowRuntimeActivities_RuntimeItemId` (`RuntimeItemId`),
  CONSTRAINT `FK_WorkflowRuntimeActivities_WorkflowRuntimeItems_RuntimeItemId` FOREIGN KEY (`RuntimeItemId`) REFERENCES `workflowruntimeitems` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


CREATE TABLE `workflowruntimeactors` (
  `Id` char(36) NOT NULL COMMENT '工作流完成时处理人表主键(GUID)',
  `RuntimeStepId` char(36) NOT NULL COMMENT '进行时工作流步骤主键(workflowruntimesteps.Id)',
  `UserId` char(36) NOT NULL COMMENT '用户Id',
  `FullName` varchar(50) NOT NULL COMMENT '用户姓名',
  `LoginName` varchar(100) DEFAULT NULL COMMENT '用户登录名',
  `Notified` bit(1) NOT NULL COMMENT '是否通知',
  `NotifiedAt` datetime(6) DEFAULT NULL COMMENT '通知时间',
  `Remark` longtext COMMENT '工作流完成时处理人备注',
  `Processed` bit(1) NOT NULL COMMENT '是否处理',
  `ProcessedAt` datetime(6) DEFAULT NULL COMMENT '处理时间',
  `WorkflowHandlingStatusId` char(36) DEFAULT NULL COMMENT '工作流处理状态表主键(workflowhandlingstatus.Id)',
  `Status` varchar(50) DEFAULT NULL COMMENT '处理状态',
  `Active` bit(1) NOT NULL COMMENT '是否活动',
  `IsAgent` bit(1) NOT NULL COMMENT '是否为代理人',
  `AgentActorId` char(36) DEFAULT NULL COMMENT '指定处理人Id',
  `IsDelegate` bit(1) NOT NULL COMMENT '是否为委托人',
  `DelegateActorId` char(36) DEFAULT NULL COMMENT '委托人Id',
  `Reason` longtext COMMENT '指定处理人原因',
  `OriginName` varchar(50) DEFAULT NULL COMMENT '原处理人姓名',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `NON-Active` (`Active`),
  KEY `IX_WorkflowRuntimeActors_WorkflowHandlingStatusId` (`WorkflowHandlingStatusId`),
  KEY `NON-UserId` (`UserId`),
  KEY `NON-Processed` (`Processed`),
  KEY `IX_WorkflowRuntimeActors_RuntimeStepId` (`RuntimeStepId`),
  CONSTRAINT `FK_WorkflowRuntimeActors_WorkflowHandlingStatus_WorkflowHandlin~` FOREIGN KEY (`WorkflowHandlingStatusId`) REFERENCES `workflowhandlingstatus` (`Id`),
  CONSTRAINT `FK_WorkflowRuntimeActors_WorkflowRuntimeSteps_RuntimeStepId` FOREIGN KEY (`RuntimeStepId`) REFERENCES `workflowruntimesteps` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


CREATE TABLE `workflowruntimeattachments` (
  `Id` char(36) NOT NULL COMMENT '工作流进行时加签附件表主键(GUID)',
  `RuntimeCommentId` char(36) NOT NULL COMMENT '工作流进行时加签表主键(workflowruntimecomments.Id)',
  `Name` varchar(256) NOT NULL COMMENT '附件名称',
  `TargetUrl` varchar(500) NOT NULL COMMENT '附件URL',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_WorkflowRuntimeAttachments_RuntimeCommentId` (`RuntimeCommentId`),
  CONSTRAINT `FK_WorkflowRuntimeAttachments_WorkflowRuntimeComments_RuntimeCo~` FOREIGN KEY (`RuntimeCommentId`) REFERENCES `workflowruntimecomments` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


CREATE TABLE `workflowruntimecomments` (
  `Id` char(36) NOT NULL COMMENT '工作流进行时加签表主键(GUID)',
  `RuntimeActorId` char(36) NOT NULL COMMENT '工作流进行时处理人表主键(workflowruntimeactors.Id)',
  `FromUserId` char(36) NOT NULL COMMENT '用户Id(加签前)',
  `FromFullName` varchar(50) NOT NULL COMMENT '加签前用户姓名',
  `FromLoginName` varchar(100) DEFAULT NULL COMMENT '加签前用户登录名',
  `ToUserId` char(36) NOT NULL COMMENT '用户Id(加签后)',
  `ToFullName` varchar(50) NOT NULL COMMENT '加签后用户姓名',
  `ToLoginName` varchar(100) DEFAULT NULL COMMENT '加签后用户登录名',
  `CommentedAt` datetime(6) NOT NULL COMMENT '提交时间',
  `Comment` longtext NOT NULL COMMENT '加签备注',
  `Notified` bit(1) NOT NULL COMMENT '是否通知',
  `NotifiedAt` datetime(6) DEFAULT NULL COMMENT '通知时间',
  `IsReply` bit(1) NOT NULL COMMENT '否是回复加签',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_WorkflowRuntimeComments_RuntimeActorId` (`RuntimeActorId`),
  CONSTRAINT `FK_WorkflowRuntimeComments_WorkflowRuntimeActors_RuntimeActorId` FOREIGN KEY (`RuntimeActorId`) REFERENCES `workflowruntimeactors` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `workflowruntimedelegatedactors` (
  `Id` char(36) NOT NULL COMMENT '工作流委派处理人表主键(GUID)',
  `WorkflowItemId` char(36) NOT NULL COMMENT '设计时工作流主键(workflowitems.Id)',
  `UserId` char(36) NOT NULL COMMENT '用户Id',
  `FullName` varchar(50) NOT NULL COMMENT '用户姓名',
  `ToUserId` char(36) NOT NULL COMMENT '用户Id(受委派人)',
  `ToName` varchar(50) NOT NULL COMMENT '用户姓名(受委派人)',
  `ToLoginName` varchar(100) DEFAULT NULL COMMENT '用户登录名(受委派人)',
  `StartAt` datetime(6) NOT NULL COMMENT '开始时间',
  `ExpiredAt` datetime(6) NOT NULL COMMENT '过期时间',
  `Remark` longtext COMMENT '备注(委派)',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_WorkflowRuntimeDelegatedActors_WorkflowItemId` (`WorkflowItemId`),
  CONSTRAINT `FK_WorkflowRuntimeDelegatedActors_WorkflowItems_WorkflowItemId` FOREIGN KEY (`WorkflowItemId`) REFERENCES `workflowitems` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `workflowruntimeitems` (
  `Id` char(36) NOT NULL COMMENT '工作流运行时表主键(GUID)',
  `WorkflowItemId` char(36) NOT NULL COMMENT '设计时工作流主键(workflowitems.Id)',
  `TargetEntityId` varchar(50) NOT NULL COMMENT '工单主单主键(tb_workorderinfo.Id)',
  `CurrentStepId` char(36) DEFAULT NULL COMMENT '当前步骤表主键(workflowruntimesteps.Id)',
  `Status` varchar(50) NOT NULL COMMENT '处理状态',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `FK_WorkflowRuntimeItems_WorkflowRuntimeSteps_CurrentStepId` (`CurrentStepId`),
  KEY `IX_WorkflowRuntimeItems_WorkflowItemId` (`WorkflowItemId`),
  KEY `NON-TargetId` (`TargetEntityId`),
  KEY `NON-Status` (`Status`),
  KEY `NON-UpdatedAt` (`UpdatedAt`),
  CONSTRAINT `FK_WorkflowRuntimeItems_WorkflowItems_WorkflowItemId` FOREIGN KEY (`WorkflowItemId`) REFERENCES `workflowitems` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_WorkflowRuntimeItems_WorkflowRuntimeSteps_CurrentStepId` FOREIGN KEY (`CurrentStepId`) REFERENCES `workflowruntimesteps` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `workflowruntimerelatedactors` (
  `Id` char(36) NOT NULL COMMENT '工作流进行时步骤知情人表主键(GUID)',
  `RuntimeStepId` char(36) NOT NULL COMMENT '工作流进行时步骤表主键(workflowruntimesteps.Id)',
  `UserId` char(36) NOT NULL COMMENT '用户Id',
  `FullName` varchar(50) NOT NULL COMMENT '用户姓名',
  `LoginName` varchar(100) DEFAULT NULL COMMENT '用户登录名',
  `Status` varchar(50) DEFAULT NULL COMMENT '处理状态',
  `Notified` bit(1) NOT NULL COMMENT '是否通知',
  `NotifiedAt` datetime(6) DEFAULT NULL COMMENT '通知时间',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `FK_WorkflowRuntimeRelatedActors_WorkflowRuntimeSteps_RuntimeSte~` (`RuntimeStepId`),
  CONSTRAINT `FK_WorkflowRuntimeRelatedActors_WorkflowRuntimeSteps_RuntimeSte~` FOREIGN KEY (`RuntimeStepId`) REFERENCES `workflowruntimesteps` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `workflowruntimereminderlogs` (
  `Id` char(36) NOT NULL COMMENT '工作流运行时提交人超时提醒记录表主键(GUID)',
  `RuntimeItemId` char(36) NOT NULL COMMENT '进行时工作流主键(workflowruntimeitems.Id)',
  `RemindedNum` int(11) NOT NULL COMMENT '提醒次数',
  `LatestRemindAt` datetime(6) NOT NULL COMMENT '最近提醒时间',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_WorkflowRuntimeReminderLogs_RuntimeItemId` (`RuntimeItemId`),
  CONSTRAINT `FK_WorkflowRuntimeReminderLogs_WorkflowRuntimeItems_RuntimeItem~` FOREIGN KEY (`RuntimeItemId`) REFERENCES `workflowruntimeitems` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


CREATE TABLE `workflowruntimestatus` (
  `Id` char(36) NOT NULL COMMENT '工作流运行时状态表主键(GUID)',
  `RuntimeItemId` char(36) NOT NULL COMMENT '进行时工作流主键(workflowcompleteitems.Id)',
  `TargetEntityId` varchar(50) NOT NULL COMMENT '工单主单主键(tb_workorderinfo.Id)',
  `WorkflowItemId` char(36) NOT NULL COMMENT '设计时工作流主键(workflowitems.Id)',
  `WorkflowItemCode` varchar(50) NOT NULL COMMENT '设计时工作流编码',
  `WorkflowStatus` varchar(50) DEFAULT NULL COMMENT '工作流状态',
  `WorkflowStatusText` varchar(50) DEFAULT NULL COMMENT '工作流状态显示名称',
  `PreStepName` varchar(50) DEFAULT NULL COMMENT '步骤名称(上一步)',
  `PreStepNodeCode` varchar(50) DEFAULT NULL COMMENT '步骤节点编码(上一步)',
  `PreStepStatus` varchar(50) DEFAULT NULL COMMENT '步骤状态(上一步)',
  `PreStepHandlingStatusName` varchar(50) DEFAULT NULL COMMENT '步骤处理状态名称(上一步)',
  `PreStepHandlingStatusCode` varchar(50) DEFAULT NULL COMMENT '步骤处理状态编码(上一步)',
  `CurrentStepName` varchar(50) DEFAULT NULL COMMENT '步骤名称(当前)',
  `CurrentStepNodeCode` varchar(50) DEFAULT NULL COMMENT '步骤节点编码(当前)',
  `CurrentStepStatus` varchar(50) DEFAULT NULL COMMENT '步骤状态(当前)',
  `Remark` varchar(256) DEFAULT NULL COMMENT '备注',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `NON-TargetId` (`TargetEntityId`),
  KEY `NON-RuntimeItemId` (`RuntimeItemId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `workflowruntimesteps` (
  `Id` char(36) NOT NULL COMMENT '工作流进行时步骤表主键(GUID)',
  `RuntimeItemId` char(36) NOT NULL COMMENT '进行时工作流主键(workflowruntimeitems.Id)',
  `WorkflowNodeId` char(36) DEFAULT NULL COMMENT '设计时工作流节点主键(workflownodes.Id)',
  `Name` varchar(256) NOT NULL COMMENT '步骤名称',
  `SortOrder` int(11) NOT NULL,
  `StartedAt` datetime(6) NOT NULL COMMENT '开始时间',
  `DoneAt` datetime(6) DEFAULT NULL COMMENT '结束时间',
  `ActorNumber` int(11) NOT NULL COMMENT '处理人数',
  `AcceptedNumber` int(11) NOT NULL COMMENT '通过人数',
  `DeclinedNumber` int(11) NOT NULL COMMENT '拒绝人数',
  `Status` varchar(50) DEFAULT NULL COMMENT '步骤状态',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `FK_WorkflowRuntimeSteps_WorkflowRuntimeItems_RuntimeItemId` (`RuntimeItemId`),
  KEY `NON-Status` (`Status`),
  KEY `NON-DoneAt` (`DoneAt`),
  KEY `NON-Name` (`Name`),
  KEY `FK_WorkflowRuntimeSteps_WorkflowNodes_WorkflowNodeId` (`WorkflowNodeId`),
  KEY `NON-StartAt` (`StartedAt`),
  KEY `NON-SortOrder` (`SortOrder`),
  CONSTRAINT `FK_WorkflowRuntimeSteps_WorkflowNodes_WorkflowNodeId` FOREIGN KEY (`WorkflowNodeId`) REFERENCES `workflownodes` (`Id`),
  CONSTRAINT `FK_WorkflowRuntimeSteps_WorkflowRuntimeItems_RuntimeItemId` FOREIGN KEY (`RuntimeItemId`) REFERENCES `workflowruntimeitems` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `workflowruntimesubscribemsgs` (
  `Id` char(36) NOT NULL COMMENT '工作流处理人订阅消息配置表主键(GUID)',
  `UserId` char(36) NOT NULL COMMENT '用户Id',
  `FullName` varchar(50) NOT NULL COMMENT '用户姓名',
  `LoginName` varchar(100) NOT NULL COMMENT '用户登录名',
  `SubscriptionType` varchar(50) NOT NULL COMMENT '订阅消息类型',
  `TimingAtTime` varchar(50) DEFAULT NULL COMMENT '定时时间',
  `IntervalHour` int(11) NOT NULL COMMENT '间隔时间(小时)',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `workflowruntimetimingmsgsends` (
  `Id` char(36) NOT NULL COMMENT '工作流运行时定时消息表主键(GUID)',
  `UserId` char(36) NOT NULL COMMENT '用户Id',
  `FullName` varchar(50) NOT NULL COMMENT '用户姓名',
  `LoginName` varchar(100) NOT NULL COMMENT '用户登录名',
  `Subject` varchar(50) NOT NULL COMMENT '说明',
  `Message` longtext NOT NULL COMMENT '消息内容',
  `WorkFlowItemCode` longtext COMMENT '设计时工作流编码',
  `Sent` bit(1) NOT NULL COMMENT '是否发送',
  `SendAt` datetime(6) NOT NULL COMMENT '发送时间',
  `CreatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CreatedAt` datetime(6) DEFAULT NULL,
  `UpdatedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT NULL,
  `Deleted` bit(1) NOT NULL,
  `DeletedById` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `DeletedAt` datetime(6) DEFAULT NULL,
  `AllowAutomaticAudit` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

